//PokemonsContainer
export const GETING_STARTS = "GETING_STARTS";
export const GETING_ENDS = "GETING_ENDS";
export const GETED_SUCCESS = "GETED_SUCCESS";
export const GETED_ERROR = "GETED_ERROR";
export const SEARCH_HANDLER = "SEARCH_HANDLER";

//PokemonsPage
export const GETING_POKEMON_STARTS = "GETING_POKEMON_STARTS";
export const GETING_POKEMON_ENDS = "GETING_POKEMON_ENDS";
export const GETED_POKEMON_SUCCESS = "GETED_POKEMON_SUCCESS";
export const GETED_POKEMON_ERROR = "GETED_POKEMON_ERROR";

//AbiliyInfo
export const GETING_ABILITY_STARTS = "GETING_ABILITY_STARTS";
export const GETING_ABILITY_ENDS = "GETING_ABILITY_ENDS";
export const GETED_ABILITY_SUCCESS = "GETED_ABILITY_SUCCESS";
export const GETED_ABILITY_ERROR = "GETED_ABILITY_ERROR";

